#!/usr/bin/env python
#
# Copyright (C) 2013
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
'''
Created on 12.02.2013

@author: ajazdzewski
'''
import sys
import os
from common import config
from common import rados

if __name__ == '__main__':
    __CONF = config.config('storage.conf')
    _RBD = rados.RBD()

    __result__ = _RBD.grow(
        os.getenv('VOL_NAME'),
        os.getenv('VOL_NEW_SIZE'),
        __CONF.pool)
    if __result__ is True:
        sys.exit(0)
    sys.exit(1)
